name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "travelmaker-api"
          heroku_email: "marcin.dobroszek@gmail.com"
        env:
          HD_DATABASE: ${{ secrets.DATABASE }}
          HD_PORT: 80
